# Custom events
MOVED_TOWARDS_COIN = "MOVED_TOWARDS_COIN"
MOVED_AWAY_FROM_COIN = "MOVED_AWAY_FROM_COIN"
MOVED_TOWARDS_CRATE = "MOVED_TOWARDS_CRATE"
MOVED_AWAY_FROM_CRATE = "MOVED_AWAY_FROM_CRATE"
MOVED_TO_SAFETY = "MOVED_TO_SAFETY"
STAYED_IN_DANGER = "STAYED_IN_DANGER"
BOMB_PLACED_NEAR_ENEMY = "BOMB_PLACED_NEAR_ENEMY"
USEFUL_BOMB = "USEFUL_BOMB"
USELESS_BOMB = "USELESS_BOMB"
EXPLORED_NEW_TILE = "EXPLORED_NEW_TILE"  # Reward for visiting new tiles
AGENT_BLOCKED = "AGENT_BLOCKED"  # Agent tried to move but was blocked